/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ExplanationRouteImport } from './routes/explanation'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplanationRoute = ExplanationRouteImport.update({
  id: '/explanation',
  path: '/explanation',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnosis': typeof DiagnosisRoute
  '/explanation': typeof ExplanationRoute
  '/goals': typeof GoalsRoute
  '/profile': typeof ProfileRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnosis': typeof DiagnosisRoute
  '/explanation': typeof ExplanationRoute
  '/goals': typeof GoalsRoute
  '/profile': typeof ProfileRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnosis': typeof DiagnosisRoute
  '/explanation': typeof ExplanationRoute
  '/goals': typeof GoalsRoute
  '/profile': typeof ProfileRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/diagnosis'
    | '/explanation'
    | '/goals'
    | '/profile'
    | '/recommendation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/diagnosis'
    | '/explanation'
    | '/goals'
    | '/profile'
    | '/recommendation'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/diagnosis'
    | '/explanation'
    | '/goals'
    | '/profile'
    | '/recommendation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosisRoute: typeof DiagnosisRoute
  ExplanationRoute: typeof ExplanationRoute
  GoalsRoute: typeof GoalsRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationRoute: typeof RecommendationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explanation': {
      id: '/explanation'
      path: '/explanation'
      fullPath: '/explanation'
      preLoaderRoute: typeof ExplanationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DiagnosisRoute: DiagnosisRoute,
  ExplanationRoute: ExplanationRoute,
  GoalsRoute: GoalsRoute,
  ProfileRoute: ProfileRoute,
  RecommendationRoute: RecommendationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
